# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  appName: 'setdatapro'
  env: 'dev'
  deployment.region: 'us-east-1'
  deployment.workers: '1'
  deployment.workerType: 'MICRO'
  http.port: '8081'

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean deploy'
    options: >
      -Danypoint.username=$(ANYPOINT_USERNAME)
      -Danypoint.password=$(ANYPOINT_PASSWORD)
      -Denv=$(env)
      -Ddeployment.region=$(deployment.region)
      -Ddeployment.workers=$(deployment.workers)
      -Ddeployment.workerType=$(deployment.workerType)
      -Dhttp.port=$(http.port)
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    mavenOptions: '-Xmx1024m'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'target'
    ArtifactName: 'mule-artifact'
    publishLocation: 'Container'
